import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
      )}
    >
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {`(() => {
            const storageKey = 'theme';
            const root = document.documentElement;
            const storedTheme = localStorage.getItem(storageKey);
            const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
            const theme = storedTheme === 'dark' || storedTheme === 'light' ? storedTheme : systemTheme;
            root.classList.toggle('dark', theme === 'dark');
            root.style.colorScheme = theme;
          })();`}
        </Script>
      </head>
      <body className="min-h-full flex flex-col bg-background text-foreground px-4 sm:px-6 md:px-10">
        {children}
      </body>
    </html>
  );
}
